package com.example.filemanager.greendao;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.filemanager.entity.UserContract;

import com.example.filemanager.greendao.UserContractDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userContractDaoConfig;

    private final UserContractDao userContractDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userContractDaoConfig = daoConfigMap.get(UserContractDao.class).clone();
        userContractDaoConfig.initIdentityScope(type);

        userContractDao = new UserContractDao(userContractDaoConfig, this);

        registerDao(UserContract.class, userContractDao);
    }
    
    public void clear() {
        userContractDaoConfig.clearIdentityScope();
    }

    public UserContractDao getUserContractDao() {
        return userContractDao;
    }

}
